version: 0.0
os: linux
files:
  #現在のディレクトリをEC2のアプリケーションにデプロイする設定
  - source: /
    destination: /var/www/code4-product-register
permissins:
  #/var/www 以下の全てのディレクトリに755の権限を設定
  - object: /var/www/
    pattern: '**'
    mode: 775
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
