version: 0.2

phases:
  #codebuild から S3 に渡すとき。
  install:
    commands:
      - bundle install
  build:
    commands:
      - rails db:create RAILS_ENV=production
      - rails db:migrate RAILS_ENV=production
      - rails assets:precompile RAILS_ENV=production
artifacts:
  files:
    - './**/*'
