version: 0.2

phases:
  #codebuild から S3 に渡すとき。
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - rbenv install 2.5.9
      - gem install bundler -v 1.17.3
      - bundle install --path vendor/bundle
  build:
    commands:
      - rails assets:precompile RAILS_ENV=production
artifacts:
  files:
    - './**/*'
