version: 0.2

phases:
  #codebuild から S3 に渡すとき。
  install:
    commands:
      - bundle install --path vendor/bundle
  build:
    commands:
      - rails assets:precompile RAILS_ENV=production
artifacts:
  files:
    - './**/*'
