version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/code4-product-register'
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      DB_HOST: db
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
