version: 2.1
jobs:
  build:
    docker:
      #以降のコマンドは一つ目のイメージをベースに実行
      - image: circleci/ruby:2.5.9-node-browsers
        environment:
          - RAILS_ENV: 'test'
      - image: circleci/mysql:5.6
        environment:
          - MYSQL_ROOT_PASSWORD: password
    environment:
      # circleci/mysql:5.6がポートを EXPOSE しているので、一つ目のコンテナでlocalhost からフォワードできる様になっている
      # `localhost:3306` で circleci/mysql:5.6に接続可能
      #portがdatabase.yml 3306を指定
      DB_HOST: 127.0.0.1
    steps:
      - pwd
      - checkout
      - pwd
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          #自分のアプリで使っているbundler のバージョンを設定
          command: |
            gem install bundler -v 1.17.3
            bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: データベースの作成
          command: bundle exec rake db:create
      - run:
          name: データベースのマイグレーション
          command: bundle exec rake db:migrate
      - run:
          name: run tests
          command: bin/rspec
  # deploy_tmp:
  #   docker:
  #     - image: circleci/ruby:2.5.9-node-browsers
  #   steps:
  #     - checkout
  #     - add_ssh_keys
  #     - run:
  #         name: deploy to prod
  #         command: |
  #           echo -e "Host git-codecommit.*.amazonaws.com\n   User ${AWS_SSH_KEY_ID}\n   StrictHostKeyChecking no" > ${HOME}/.ssh/config
  #           git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/product-ec2
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      # - deploy_tmp:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - master
