default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){5}%>
  username: webuser

development:
  <<: *default
  database: product_register_new_development

test:
  <<: *default
  database: product_register_new_test

production:
  <<: *default
  database: product_register_new_production
  password: <%= ENV['DATABASE_PASSWORD']%>
  socket: /var/lib/mysql/mysql.sock
  host: database-product.cz1ouy4op612.ap-northeast-1.rds.amazonaws.com
