default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){5}%>

development:
  <<: *default
  username: root
  password: asdy164g
  database: product_register_new_development
  host: db

test:
  <<: *default
  database: product_register_new_test

production:
  <<: *default
  database: product_register_new_production
  password: <%= ENV['DATABASE_PASSWORD']%>
  socket: /var/lib/mysql/mysql.sock
  username: admin
  host: database-product.cz1ouy4op612.ap-northeast-1.rds.amazonaws.com
